/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface RenderOptions {
  /** Maximum time to wait for rendering in milliseconds */
  timeout?: number
  /** CSS selector to wait for before capturing HTML */
  waitFor?: string
  /** CSS selector to extract (returns only matching element's HTML) */
  selector?: string
  /** JavaScript code to execute before capturing HTML */
  script?: string
}
/** Renders a webpage using a native WebView and returns the final HTML */
export declare function renderPage(url: string, options?: RenderOptions | undefined | null): string
