/**
 * Native module loader
 *
 * This file handles loading the platform-specific native module.
 * The actual .node file is loaded by the index.js generated by napi-rs.
 */

// Dynamic import of the native module
// The napi-rs build generates index.js at the project root
let nativeModule;

try {
  // Try to load from the napi-generated index.cjs
  // This works whether we're in development or published package
  const imported = await import('../index.cjs');
  nativeModule = imported;
} catch (err) {
  throw new Error(
    `Failed to load native module: ${err.message}\n\n` +
    `This usually means:\n` +
    `1. The native module hasn't been built yet - run 'npm run build'\n` +
    `2. You're on an unsupported platform\n` +
    `3. Platform dependencies are missing (e.g., WebKitGTK on Linux)\n\n` +
    `See INSTALLATION.md for platform-specific requirements.`
  );
}

export const { renderPage } = nativeModule;
